# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Team 6353 | Zodiac
email:
description: Team 6353 Zodiac is a FIRST Robotics Competition Team.
baseurl: ""

# Build settings
markdown: CustomRedcarpetParser

assets:
  compress:
    css: true
    js: true

  autowrite: true
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true

exclude:
  - vendor
  - README.md
